### ISSUE TITLE
Address remaining review comments from @trishankkarthik

### ISSUE THREAD

**Issue by lukpueh** [in-toto/docs#14]
@SantiagoTorres partially addressed an out-of-band specification review from @trishankkarthik in #6. As per the PR description *(Oct 2017)* the following items remained:

- [ ] There are too many terms upfront 
- [ ] Sections 2-3 are particularly redundant
- [ ] More pictures and diagrams are necessary (ASK) 
- [ ] POSIX timestamps
- [ ] Point 8 of minor readability issues (ask trishank) 
- [ ] Why is there mention of private keys in the metadata? 
- [ ] Commands sound dangerous, are clients expected to run arbitrary commands? (ASK/Debate/FAQ) 
 - [ ] What about rollback attacks? (Elaborate/question)

**Comment by trishankkarthik** [comment]
cc @trishankatdatadog

**Comment by adityasaky** [comment]
@trishankkarthik @trishankatdatadog could you review this and see if we still need to address the points here? I think several points have been fixed over the years.

**Comment by trishankatdatadog** [comment]
I think we can close this for now and address new comments afresh. Thanks!
