### ISSUE TITLE
key format specification is inconsistent

### ISSUE THREAD

**Issue by shibumi** [in-toto/docs#33]
Hi there,
Right now our specification specifies the following key format:

```
  { "keytype" : "<KEYTYPE>",
    "scheme" : "<SCHEME>",
    "keyval" : "<KEYVAL>" }
```
Source: https://github.com/in-toto/docs/blob/master/in-toto-spec.md#42-file-formats-general-principles

However, if you generate a new ed25519 key with `in-toto-keygen.py` you will end up with the following  private and public key.
private:
```
{
  "keytype": "ed25519",
  "scheme": "ed25519",
  "keyid": "d7c0baabc90b7bf218aa67461ec0c3c7f13a8a5d8552859c8fafe41588be01cf",
  "keyid_hash_algorithms": ["sha256", "sha512"],
  "keyval": {
    "public": "8c93f633f2378cc64dd7cbb0ed35eac59e1f28065f90cbbddb59878436fec037",
    "private": "4cedf4d3369f8c83af472d0d329aedaa86265b74efb74b708f6a1ed23f290162"}
}
```

public:
```
{"keytype": "ed25519",
"scheme": "ed25519",
"keyid_hash_algorithms": ["sha256", "sha512"],
"keyval": {"public": "8c93f633f2378cc64dd7cbb0ed35eac59e1f28065f90cbbddb59878436fec037"}}
```

In the public key the keyID is missing. Is this on purpose?

**Comment by lukpueh** [comment]
Thanks for pointing this out, I'm completely against adding `keyid_hash_algorithms` to the spec, and I also vote for removing it from the reference implementation (see https://github.com/theupdateframework/tuf/issues/848 for controversy around this field).

Regarding the `keyid`, it does not really seem necessary to include it in the key object, because each key object is identified by its keyid (as dict key) in the keys dictionary.

So I think we should remove it in the reference implementation, unless I'm missing a good reason (@SantiagoTorres?).

**Comment by adityasaky** [comment]
I'd also prefer not to add it to the spec. I wondered if we wanted to allow additional fields but that's also going to lead to more incompatibility. I'm in favour of removing it from the implementations and making certain assumptions there instead. Can we track this in the implementations?

cc @lukpueh

**Comment by lukpueh** [comment]
> Can we track this in the implementations?

👍 

https://github.com/secure-systems-lab/securesystemslib/issues/308 should be helpful to create more succinct issues of in python-tuf and in-toto.

**Comment by adityasaky** [comment]
Closing in favour of the sslib issue, feel free to reopen if we need to have a spec discussion as well!

**Comment by adityasaky** [comment]
I think updating those specifications is worthwhile, though we're working on deprecating -golang in favour of witness and go-witness. This shouldn't affect verifying old links against old layouts as the keyids would be internally consistent, but I suppose this breaks new links (post implementation update) verified against old layouts? I don't recall if the key ID is only used as a hint with a fallback option. cc @lukpueh
