### ISSUE TITLE
Tag v1.0 of the spec

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/docs#46]
Given that ITE-5 and ITE-6 intend to significantly change the spec, it is useful to be able to link to the current revision. The v0.9 tag is too old - it does not yet include "environment".

Could you bump up the revision of docs/in-toto-spec.md and create a git tag? I'm guessing this would be called v1.0?

**Comment by adityasaky** [comment]
With #75, in-toto-spec was updated to v1.0-RC. I'm going to revive this thread to track comments and so on that should block a formal v1.0.
