### ISSUE TITLE
Diagrams that show up in various places are not viewable in darkmode.

### ISSUE THREAD

**Issue by Alos** [in-toto/docs#52]
If you use GitHub in darkmode, some of the diagrams can't be seen as they rely on white background. i.e https://github.com/in-toto/docs/blob/master/in-toto-spec.md has a diagram but you can't see the arrows.

**Comment by adityasaky** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/8928778/212552714-b4d439be-ea69-4820-b6a5-a9381c706c88.png)
