### ISSUE TITLE
Broken Hyperlinks in in-toto-spec.pdf

### ISSUE THREAD

**Issue by lakshya8066** [in-toto/docs#63]
The hyperlinks in the table of contents of the in-toto-spec.pdf seem to be broken. 
![image](https://user-images.githubusercontent.com/73181332/178423361-8ed7f813-f2cf-44eb-89ed-08dad4cf131e.png)

**Comment by adityasaky** [comment]
Whoops, looks like the PDF generation created absolute links instead of relative. The PDF has been removed altogether now, so I'm closing this issue.
