### ISSUE TITLE
Potential grammatical error

### ISSUE THREAD

**Issue by ChaosInTheCRD** [in-toto/docs#81]
Hi there 👋 

I am just reading through the spec and I noticed a small sentence that might be a grammatical error? I just thought it would be worth raising in case it needed a cleanup. The line in question is [L431-L432](https://github.com/in-toto/docs/blob/v1.0/in-toto-spec.md?plain=1#L431-L432):

> A functionary can allow a third-party define a step or series of steps of the supply chain a sublayout

I was thinking maybe this is meant to read as something like:

> A functionary can allow a third-party to define a step or series of steps of the supply chain known as a sublayout

Maybe grammatically the current sentence is technically correct, it just didn't quite read correct to me.

Thanks 😄

**Comment by JustinCappos** [comment]
I agree this is broken and your fix would correct it.  Would you like to submit a PR and we can accept?

**Comment by ChaosInTheCRD** [comment]
Hi both, I'll go ahead and submit a PR as suggested - thank you for the quick response!

**Comment by ChaosInTheCRD** [comment]
https://github.com/in-toto/docs/pull/82
